### ISSUE TITLE
Collaborate with EasySync

### ISSUE THREAD

**Issue by stokito** [bigCrash/SyncOSS#1]
It looks like you stopped working on the project but maye you can contribute to the similar project https://github.com/phpbg/easysync

**Comment by jdannenberg** [comment]
Hi @stokito. Actually, I stumbled across syncthing some long time ago which is why I did not continue this project. Syncthing is pretty awesome and by far the best syncing app for Android I have ever used. Thus, Syncthing is now deeply integrated into my infrastructure. I am syncing to a samba share but you surely could also sync to a webdav share.

This sadly means I have not much interest to invest in other projects (including mine). There would be a lot A LOT of work involved to come somehow close to Syncthing. But as always, diversification is awesome so don't let that drown your motivation, I appreciate that.
